### ISSUE TITLE
Planificación Sprint 2

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga#20]
### Brainstorming

**Vista general de tareas**
![img_20190207_113357](https://user-images.githubusercontent.com/5110813/52406925-29d60700-2acf-11e9-80ee-f9ba6c894bc4.jpg)

**División de tareas y trabajo en paralelo**

![img_20190207_115137](https://user-images.githubusercontent.com/5110813/52406919-25a9e980-2acf-11e9-9d9e-01b936af3633.jpg)

### Referencia del Router

**Notas**
- Solo tenemos un fichero html que contiene `footer`, `header`, `nav`, etc... llamado `index.html`
- Tenemos varias vistas que están dentro de un `div`/`section` contenedor 
- No tenemos listo el diseño de usuario por lo que aplazamos esa vista.
- ¿Qué vistas tenemos?
    - `home`: lorem ipsum + CTA `Vamos alla!`
    - `galería (step-1)`: previsualización de templates de memes, filtros y buscador...
    - `generador (step-2)`: generador y previsualizador de memes
    - `descargalo (step-3)`: descargar el meme previsualizado

**Rutas**
- `/` -> renderiza vista `home`
- `/gallery` -> renderizar vista `galería`
- `/generador/:id` -> renderiza la vista `generador` con los datos de un meme en concreto `id`
    - Si `id` no se encuentra... vuelta a galería
    - Necesitamos gestionar parámetros opcionales como `topText`, `bottomText`, `typo`, `color`, lo que reactualiza la vista, ejemplo `/generador/:id?topText=Lorem%20Ipsum&bottomText=Lorem%20Ipsum&color=%23FFF`  
- `download/:id` es como la ruta de generación pero pinta otra vista, ejemplo `/download/:id?topText=Lorem%20Ipsum&bottomText=Lorem%20Ipsum&color=%23FF
    - Si `id` no se encuentra... vuelta a galería
    - Necesitamos gestionar parámetros opcionales como `topText`, `bottomText`, `typo`, `color`, lo que reactualiza la vista, ejemplo `/generador/:id?

**Comment by Fa-v** [comment]
Pregunta, usamos módulos para la lógica de cada una de las vistas e importamos todo en el main.js?
