### ISSUE TITLE
Esqueleto + Automatizacion!

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga#3]
### Objectivos
- [x] Definir guia de estilos de JS, Sass, etc... - buscar la de airbnb, p.ej. e incluir en el `readme.md` -> @KoolTheba 
- [x] Generar todos los mocks, ver #5, #9, #10, #11 -> @KoolTheba 
- [x] Definir el esqueleto del proyecto 
- [x] Definir las tareas por automatizar (Sass, Babel, Jasmine testing, etc...)
- [x] Generar el `gulpfile`

**Comment by KoolTheba** [comment]
- Revisar cómo instalar como dependencia Boostrap y Sass en Gulp

**Comment by KoolTheba** [comment]
Quedarían pequeños detalles para resolver:
- [x] Color background navbar dinámico cuando scroll hacia abajo (jQuery?)
- [x] Mirar si necesitamos alguna media query
