### ISSUE TITLE
Implementar Firebase

### ISSUE THREAD

**Issue by UlisesGascon** [memezinga/memezinga#4]
### Objetivos
- [x] Crear los entornos en local para cada una
- [x] Crear el firebase corporativo (@UlisesGascon )
- [x]  Definir la estructura de datos (usuarios, metadatos de ficheros, etc...)
- [x] Definir la estructura de los ficheros (templates de memes)
- [x] Definir la estructura de usuarios (login)
- [x] Implementar la conexión a Firebase en el proyecto a nivel de html

**Comment by KoolTheba** [comment]
- Lo haremos juntas!
